### ISSUE TITLE
0.0.3 release needed

### ISSUE THREAD

**Issue by iamdustan** [ngryman/raf.js#5]
Just went to grab the updates you’ve pushed out these past few days and noticed a 0.0.3 tag isn’t pushed out yet.

I’m including this polyfill in a bundled version of my scrollTo smooth polyfill. https://github.com/iamdustan/smoothscroll

**Comment by ngryman** [comment]
Oh yes sorry. Pushed: https://github.com/ngryman/raf.js/releases/tag/v0.0.3.

**Comment by iamdustan** [comment]
Thank you, thank you!
